#Task21 -> Linear algebra and calculus in NumPy

#Linear Algebra Tasks

##1. Matrix Creation and Manipulation

###Create various types of matrices (zero matrix, identity matrix, random matrix

In [2]:
import numpy as np

# Zero matrix
zero_matrix = np.zeros((3, 3))

# Identity matrix
identity_matrix = np.eye(3)

# Random matrix
random_matrix = np.random.rand(3, 3)

print("Zero Matrix:\n", zero_matrix)
print('\n')
print("Identity Matrix:\n", identity_matrix)
print('\n')
print("Random Matrix:\n", random_matrix)


Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Random Matrix:
 [[0.69628986 0.88620407 0.15515523]
 [0.57596181 0.02247378 0.84833683]
 [0.51450851 0.86122974 0.19379243]]


###Perform basic matrix operations (addition, subtraction, multiplication).

In [4]:
# Matrix addition
matrix_sum = random_matrix + identity_matrix

# Matrix subtraction
matrix_diff = random_matrix - identity_matrix

# Matrix multiplication
matrix_product = np.dot(random_matrix, identity_matrix)

print("Matrix Sum:\n", matrix_sum)
print('\n')
print("Matrix Difference:\n", matrix_diff)
print('\n')
print("Matrix Product:\n", matrix_product)


Matrix Sum:
 [[1.69628986 0.88620407 0.15515523]
 [0.57596181 1.02247378 0.84833683]
 [0.51450851 0.86122974 1.19379243]]


Matrix Difference:
 [[-0.30371014  0.88620407  0.15515523]
 [ 0.57596181 -0.97752622  0.84833683]
 [ 0.51450851  0.86122974 -0.80620757]]


Matrix Product:
 [[0.69628986 0.88620407 0.15515523]
 [0.57596181 0.02247378 0.84833683]
 [0.51450851 0.86122974 0.19379243]]


###Transpose a matrix and find the determinant and inverse of a matrix.

In [5]:
# Transpose
transpose_matrix = np.transpose(random_matrix)

# Determinant
determinant = np.linalg.det(random_matrix)

# Inverse
inverse_matrix = np.linalg.inv(random_matrix)

print("Transpose Matrix:\n", transpose_matrix)
print('\n')
print("Determinant:\n", determinant)
print('\n')
print("Inverse Matrix:\n", inverse_matrix)


Transpose Matrix:
 [[0.69628986 0.57596181 0.51450851]
 [0.88620407 0.02247378 0.86122974]
 [0.15515523 0.84833683 0.19379243]]


Determinant:
 -0.14262561529986031


Inverse Matrix:
 [[ 5.09205628  0.2672405  -5.24669163]
 [-2.27770782 -0.38637532  3.51497062]
 [-3.3968126   1.00757501  3.46902222]]


##2. Solving Linear Equations

###Use NumPy to solve a system of linear equations.

In [45]:
# Coefficient matrix
A = np.array([[3, 1], [1, 2]])

# Dependent variable matrix
b = np.array([9, 8])

x = np.linalg.solve(A, b)
print("Solution of the system:\n", x)


Solution of the system:
 [2. 3.]


###Implement matrix factorization methods (LU decomposition, QR decomposition).

In [9]:
# LU decomposition
from scipy.linalg import lu
P, L, U = lu(A)
print("LU Decomposition:\nP:\n", P, "\nL:\n", L, "\nU:\n", U)
print('\n')
# QR decomposition
Q, R = np.linalg.qr(A)
print("QR Decomposition:\nQ:\n", Q, "\nR:\n", R)


LU Decomposition:
P:
 [[1. 0.]
 [0. 1.]] 
L:
 [[1.         0.        ]
 [0.33333333 1.        ]] 
U:
 [[3.         1.        ]
 [0.         1.66666667]]


QR Decomposition:
Q:
 [[-0.9486833  -0.31622777]
 [-0.31622777  0.9486833 ]] 
R:
 [[-3.16227766 -1.58113883]
 [ 0.          1.58113883]]


##3. Eigenvalues and Eigenvectors

###Calculate the eigenvalues and eigenvectors of a given matrix.

In [44]:
eigenvalues, eigenvectors = np.linalg.eig(A) # I take matrix A to get its eigen values and eigen vectors
print("Eigenvalues:\n", eigenvalues)
print('\n')
print("Eigenvectors:\n", eigenvectors)



Eigenvalues:
 [3.61803399 1.38196601]


Eigenvectors:
 [[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]


###Verify the results by reconstructing the original matrix.

In [14]:
reconstructed_A = eigenvectors @ np.diag(eigenvalues) @ np.linalg.inv(eigenvectors)
print("Reconstructed A:\n", reconstructed_A)

Reconstructed A:
 [[3. 1.]
 [1. 2.]]


##4. Vector Operations

###Perform basic vector operations (addition, dot product, cross product).

In [43]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Addition
v_add = v1 + v2

# Dot product
v_dot = np.dot(v1, v2)

# Cross product
v_cross = np.cross(v1, v2)



print("Vector Addition:\n", v_add)
print('\n')
print("Dot Product:\n", v_dot)
print('\n')
print("Cross Product:\n", v_cross)



Vector Addition:
 [5 7 9]


Dot Product:
 32


Cross Product:
 [-3  6 -3]


###Normalize a vector and compute vector norms.

In [42]:
v1_norm = np.linalg.norm(v1)
v1_normalized = v1 / v1_norm
print("Normalized Vector:\n", v1_normalized)

Normalized Vector:
 [0.26726124 0.53452248 0.80178373]


##5. Matrix Decomposition

###Understand and implement Principal Component Analysis (PCA) using SVD.

In [47]:
X = np.random.rand(5, 3)

# Perform SVD
U, S, VT = np.linalg.svd(X, full_matrices=False)

# Principal components
PCs = U @ np.diag(S)

print("Principal Components:\n", PCs)


Principal Components:
 [[-1.21748583  0.05774512 -0.25140322]
 [-0.5702674  -0.67558774  0.0369478 ]
 [-0.5729234   0.11273787  0.25734225]
 [-0.81803312  0.10855471  0.39718203]
 [-0.96283836  0.16780624 -0.19456612]]


#Calculus Tasks

##1. Numerical Differentiation

###Use NumPy to compute the numerical derivative of a given function.

###Implement forward, backward, and central difference methods for differentiation.

In [24]:
def f(x):
    return x**2

x = np.array([2.0])

# Forward difference
def forward_diff(f, x, h=1e-5):
    return (f(x + h) - f(x)) / h

# Backward difference
def backward_diff(f, x, h=1e-5):
    return (f(x) - f(x - h)) / h

# Central difference
def central_diff(f, x, h=1e-5):
    return (f(x + h) - f(x - h)) / (2 * h)

print("Forward Difference:\n", forward_diff(f, x))
print('\n')
print("Backward Difference:\n", backward_diff(f, x))
print('\n')
print("Central Difference:\n", central_diff(f, x))

Forward Difference:
 [4.00001]


Backward Difference:
 [3.99999]


Central Difference:
 [4.]


##2. Numerical Integration

###Use NumPy to compute the numerical integral of a given function.

###Implement the trapezoidal rule and Simpson's rule for integration.

In [30]:
def g(x):
    return z**2 + y**2

y = np.array([3.0])
z = np.array([6.0])

# Trapezoidal rule
def trapezoidal_rule(g, a, b, n):
    x = np.linspace(a, b, n+1)
    p = g(x)
    return (b - a) * (np.sum(p) - (p[0] + p[-1]) / 2) / n

# Simpson's rule
def simpsons_rule(g, a, b, n):
    if n % 2:
        raise ValueError("n must be even")
    x = np.linspace(a, b, n+1)
    p = g(x)
    return (b - a) / (3 * n) * (p[0] + p[-1] + 4 * np.sum(p[1:-1:2]) + 2 * np.sum(p[2:-2:2]))

a, b, n = 0, 1, 100
print("Trapezoidal Rule:\n", trapezoidal_rule(g, a, b, n))
print('\n')
print("Simpson's Rule:\n", simpsons_rule(g, a, b, n))

Trapezoidal Rule:
 0.0


Simpson's Rule:
 0.30000000000000004


##3. Partial Derivatives

###Calculate partial derivatives of multivariable functions using NumPy.

In [32]:
def f(x, y):
    return x**2 + y**2

def partial_x(f, x, y, h=1e-5):
    return (f(x + h, y) - f(x, y)) / h

def partial_y(f, x, y, h=1e-5):
    return (f(x, y + h) - f(x, y)) / h

x, y = 1, 2
print("Partial Derivative wrt x:\n", partial_x(f, x, y))
print('\n')
print("Partial Derivative wrt y:\n", partial_y(f, x, y))


Partial Derivative wrt x:
 2.00001000001393


Partial Derivative wrt y:
 4.000010000027032


###Verify results by comparing with analytical solutions.

In [34]:
# Analytical partial derivatives
partial_x_analytical = 2 * x
partial_y_analytical = 2 * y

print("Analytical Partial Derivative wrt x:", partial_x_analytical)
print('\n')
print("Analytical Partial Derivative wrt y:", partial_y_analytical)
print('\n')
print("The numerical partial derivatives computed are very close to the analytical partial derivatives, confirming the accuracy of the numerical methods")

Analytical Partial Derivative wrt x: 2


Analytical Partial Derivative wrt y: 4


The numerical partial derivatives computed are very close to the analytical partial derivatives, confirming the accuracy of the numerical methods


##4. Optimization

###Use NumPy to solve optimization problems with constraints.

In [48]:
def gradient_descent_with_constraint(objective, gradient, constraint, k, learning_rate=0.1, tolerance=1e-6, max_iters=1000):
    x = np.copy(k)
    for i in range(max_iters):
        grad = gradient(x)
        x = x - learning_rate * grad
        
        # Project onto the constraint set
        x -= constraint(x) * np.array([1, 1])
        
        # Check convergence
        if np.linalg.norm(grad) < tolerance:
            break
    
    return x


def objective(x):
    return x[0]**2 + x[1]**2


def gradient(x):
    return np.array([2*x[0], 2*x[1]])


def constraint(x):
    return x[0] + x[1] - 1


k = np.array([4.0, 6.0])

# Solve the optimization problem with constraints
solution = gradient_descent_with_constraint(objective, gradient, constraint, k)

print("Optimization Solution:", solution)


Optimization Solution: [0.55555556 0.55555556]
