In [3]:
import numpy as np

# 1. Create a 1D NumPy array containing the integers from 0 to 9.
array_1d = np.arange(10)# 1_D array is a single row of elements
print("1D array:", array_1d)

# 2. Create a 2D NumPy array (3x3) containing random integers between 1 and 20.
array_2d = np.random.randint(1, 21, size=(3, 3))#a matrix with rows and columns is a 2_d array
print("\n2D array (3x3) with random integers between 1 and 20:\n", array_2d)

# 3. Create a 3D NumPy array with dimensions (2, 3, 4) filled with ones.
array_3d = np.ones((2, 3, 4))#depth is 2, row is 3 and column is 4, basically a stack of 2_d arrays is a 3_d array
print("\n3D array (2, 3, 4) filled with ones:\n", array_3d)

# 4. Add two 1D arrays element-wise.
array_1d_a = np.array([1, 2, 3])
array_1d_b = np.array([4, 5, 6])
added_1d = np.add(array_1d_a, array_1d_b)
print("\nElement-wise addition of two 1D arrays:", added_1d)

# 5. Multiply two 2D arrays element-wise.
array_2d_a = np.array([[1, 2], [3, 4]])
array_2d_b = np.array([[5, 6], [7, 8]])
multiplied_2d = np.multiply(array_2d_a, array_2d_b)
print("\nElement-wise multiplication of two 2D arrays:\n", multiplied_2d)

# 6. Calculate the dot product of two matrices.
dot_product = np.dot(array_2d_a, array_2d_b)
print("\nDot product of two matrices:\n", dot_product)

# 7. Calculate the mean, median, and standard deviation of a 1D array.
mean_1d = np.mean(array_1d)
median_1d = np.median(array_1d)
std_dev_1d = np.std(array_1d)
print("\nMean of 1D array:", mean_1d)
print("Median of 1D array:", median_1d)
print("Standard deviation of 1D array:", std_dev_1d)

# 8. Find the maximum and minimum values in a 2D array.
max_2d = np.max(array_2d)
min_2d = np.min(array_2d)
print("\nMaximum value in 2D array:", max_2d)
print("Minimum value in 2D array:", min_2d)

# 9. Generate an array of 1000 random numbers from a normal distribution with a mean of 0 and a standard deviation of 1.
normal_dist_array = np.random.normal(0, 1, 1000)
print("\nArray of 1000 random numbers from a normal distribution with mean=0 and std=1:\n", normal_dist_array)

# 10. Create a 2D array of shape (5, 5) with random integers from a uniform distribution between 10 and 50.
uniform_dist_array = np.random.randint(10, 51, size=(5, 5))
print("\n2D array of shape (5, 5) with random integers from 10 to 50:\n", uniform_dist_array)

# 11. Calculate the cumulative sum of a 1D array.
cumulative_sum_1d = np.cumsum(array_1d)
print("\n sum of 1D array:", cumulative_sum_1d)

# 12. Compute the correlation coefficient matrix of a 2D array.
correlation_matrix = np.corrcoef(array_2d)
print("\nCorrelation coefficient matrix of the 2D array:\n", correlation_matrix)

# 13. Simulate rolling a six-sided die 1000 times and count the frequency of each outcome.
die_rolls = np.random.randint(1, 7, 1000)#1 row and 7 columns and rolling of 1000 times
frequency_of_outcomes = np.bincount(die_rolls)[1:]#Skipping the count of zeroes since die rolls are between 1-6 and np.bincount start counting from 0
print("\nFrequency of each outcome of rolling a six-sided die 1000 times:", frequency_of_outcomes)


1D array: [0 1 2 3 4 5 6 7 8 9]

2D array (3x3) with random integers between 1 and 20:
 [[12  3  4]
 [ 4  3 11]
 [19 10 10]]

3D array (2, 3, 4) filled with ones:
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

Element-wise addition of two 1D arrays: [5 7 9]

Element-wise multiplication of two 2D arrays:
 [[ 5 12]
 [21 32]]

Dot product of two matrices:
 [[19 22]
 [43 50]]

Mean of 1D array: 4.5
Median of 1D array: 4.5
Standard deviation of 1D array: 2.8722813232690143

Maximum value in 2D array: 19
Minimum value in 2D array: 3

Array of 1000 random numbers from a normal distribution with mean=0 and std=1:
 [ 0.59846378 -0.05562211 -0.91572458  1.08739654 -0.1314804  -2.35779872
 -0.13248564 -1.03465598  0.97742038  0.62705911  0.13881454 -0.92512631
 -1.00783877 -0.57831462 -0.70657239  1.13832748 -1.23329036 -1.04611181
  1.50537609  0.40614174  1.31466817 -1.2124992   0.52952652 -0.90971052
  0.84430924  0.43914701  0.4989402   0