In [7]:
import numpy as np

# Task 1: Extract a 3x3 sub-array starting from the element at position (1, 1) from a 2D array of shape (5, 5)
array_2d = np.arange(25).reshape(5, 5)
sub_array = array_2d[1:4, 1:4]#rows at indices 1 to 3, column at indices 1 to 3
print("Task 1:\n", sub_array, "\n")

# Task 2: Extract all elements in the first two rows and all columns of the second slice along the third axis from a 3D array of shape (4, 3, 2)
array_3d = np.arange(24).reshape(4, 3, 2)#3d array will contain elements ranging from 0 to 23, and 4 will be its depth, 3 rows and 2 columns
sub_array_3d = array_3d[:2, :, 1]#subarray of 3d will contain elements from second slice (:2), will contain all the rows in the second slice 
#and will contain the second column (index 1 ) elements.

print("Task 2 :\n", sub_array_3d, "\n")

# Task 3: Use fancy indexing to extract elements at positions [1, 3, 4, 7] from a 1D array of integers
array_1d = np.arange(10)#1d array of elements ranging from 0 to 9.
fancy_indexed = array_1d[[1, 3, 4, 7]]
print("Task 3 :\n", fancy_indexed, "\n")

# Task 4: Use fancy indexing to select rows [0, 2, 3] and columns [1, 3] from a 2D array
array_2d_fancy = np.arange(25).reshape(5, 5)  # Create a 2D array with elements ranging from 0 to 24, reshaped into a 5x5 matrix
fancy_selected = array_2d_fancy[[0, 2, 3], :][:, [1, 3]]  # Select rows 0, 2, 3 and then columns 1, 3
print("Task 4:\n", fancy_selected, "\n")  # Print the result of the fancy indexing

# Task 5: Extract all elements greater than 10 from a 1D array of random integers
random_integers = np.random.randint(0, 20, size=15)  # Create a 1D array of 15 random integers between 0 and 19
greater_than_10 = random_integers[random_integers > 10]  # Extract elements greater than 10
print("Task 5:\n", greater_than_10, "\n")  # Print the extracted elements

# Task 6: Replace all elements greater than 15 with the value 0 in a 2D array of shape (5, 5)
array_2d_replace = np.random.randint(0, 20, size=(5, 5))  # Create a 2D array of shape 5x5 with random integers between 0 and 19
array_2d_replace[array_2d_replace > 15] = 0  # Replace elements greater than 15 with 0
print("Task 6:\n", array_2d_replace, "\n")  # Print the modified array

# Task 7: Add a 1D array of shape (3,) to each row of a 2D array of shape (4, 3)
array_2d_broadcast = np.ones((4, 3))  # Create a 2D array of shape 4x3 filled with ones
array_1d = np.array([1, 2, 3])  # Create a 1D array of shape (3,)
broadcasted = array_2d_broadcast + array_1d  # Add the 1D array to each row of the 2D array using broadcasting
print("Task 7:\n", broadcasted, "\n")  # Print the result of the broadcasting

# Task 8: Multiply a 2D array of shape (3, 3) by a 1D array of shape (3,)
array_2d_multiply = np.ones((3, 3))  # Create a 2D array of shape (3, 3) filled with ones
array_1d_multiply = np.array([1, 2, 3])  # Create a 1D array of shape (3,) with elements 1, 2, and 3
multiplied = array_2d_multiply * array_1d_multiply  # Multiply each row of the 2D array by the 1D array using broadcasting
print("Task 8:\n", multiplied, "\n")  # Print the result of the multiplication

# Task 9: Create two 2D arrays of shapes (3, 1) and (1, 4) respectively, and perform element-wise addition
array_2d_3x1 = np.array([[1], [2], [3]])  # Create a 2D array of shape (3, 1) with elements 1, 2, and 3
array_2d_1x4 = np.array([[1, 2, 3, 4]])  # Create a 2D array of shape (1, 4) with elements 1, 2, 3, and 4
added = array_2d_3x1 + array_2d_1x4  # Perform element-wise addition using broadcasting
print("Task 9:\n", added, "\n")  # Print the result of the addition

# Task 10: Add a 2D array of shape (3, 4) to each 2D slice along the first axis of a 3D array of shape (2, 3, 4)
array_3d_add = np.ones((2, 3, 4))  # Create a 3D array of shape (2, 3, 4) filled with ones
array_2d_add = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])  # Create a 2D array of shape (3, 4) with specified elements
added_3d = array_3d_add + array_2d_add  # Add the 2D array to each 2D slice of the 3D array using broadcasting
print("Task 10:\n", added_3d, "\n")  # Print the result of the addition

# Task 11: Use slicing to extract every second row and every second column, then add a 1D array to each row of the sliced array
array_2d_some = np.arange(25).reshape(5, 5)  # Create a 2D array with elements ranging from 0 to 24, reshaped into a 5x5 matrix
sliced_array = array_2d_some[::2, ::2]  # Extract every second row and every second column using slicing
array_1d_add = np.array([1, 2, 3])  # Create a 1D array with elements 1, 2, and 3
added_some = sliced_array + array_1d_add[:sliced_array.shape[1]]  # Add the 1D array to each row of the sliced array using broadcasting
print("Task 11:\n", added_some, "\n")  # Print the result of the addition

# Task 12: Extract a sub-array using slicing and then use broadcasting to subtract a 2D array from each slice along the third axis from a 3D array of shape (4, 3, 2)
array_3d_sub = np.arange(24).reshape(4, 3, 2)  # Create a 3D array with elements ranging from 0 to 23, reshaped into a 4x3x2 matrix
sub_array_3d_sub = array_3d_sub[:, :, :]  # Select the entire array to maintain shape (4, 3, 2)
array_2d_subtract = np.array([[1, 2], [3, 4], [5, 6]])  # Create a 2D array of shape (3, 2)
subtracted = sub_array_3d_sub - array_2d_subtract  # Subtract the 2D array from each slice of the 3D array using broadcasting
print("Task 12:\n", subtracted, "\n")  # Print the result of the subtraction

# Task 13: Extract the diagonal elements and create a 1D array from a 2D array
array_2d_diag = np.arange(25).reshape(5, 5)  # Create a 2D array with elements ranging from 0 to 24, reshaped into a 5x5 matrix
diagonal = np.diag(array_2d_diag)  # Extract the diagonal elements and create a 1D array
print("Task 13:\n", diagonal, "\n")  # Print the diagonal elements

# Task 14: Reverse the order of elements in each row of a 2D array
array_2d_reverse = np.arange(25).reshape(5, 5)  # Create a 2D array with elements ranging from 0 to 24, reshaped into a 5x5 matrix
reversed_rows = array_2d_reverse[:, ::-1]  # Reverse the order of elements in each row using slicing
print("Task 14:\n", reversed_rows, "\n")  # Print the array with reversed rows

# Task 15: Extract a sub-array of shape (2, 3, 4) and then use broadcasting to add a 1D array of shape (4,) to each row along the third axis from a 3D array of shape (4, 5, 6)
array_3d_large = np.arange(120).reshape(4, 5, 6)  # Create a 3D array with elements ranging from 0 to 119, reshaped into a 4x5x6 matrix
sub_array_large = array_3d_large[:2, :3, :4]  # Extract a sub-array of shape (2, 3, 4)
array_1d_add_large = np.array([1, 2, 3, 4])  # Create a 1D array with elements 1, 2, 3, and 4
added_large = sub_array_large + array_1d_add_large  # Add the 1D array to each row of the sub-array using broadcasting
print("Task 15:\n", added_large, "\n")  # Print the result of the addition

# Task 16: Create a 2D array and use both slicing and broadcasting to set the last column to the sum of the first two columns for each row
array_2d_combined = np.random.randint(1, 10, (5, 5))  # Create a 2D array of shape 5x5 with random integers between 1 and 9
array_2d_combined[:, -1] = array_2d_combined[:, 0] + array_2d_combined[:, 1]  # Set the last column to the sum of the first two columns for each row
print("Task 16:\n", array_2d_combined, "\n")  # Print the modified array


Task 1:
 [[ 6  7  8]
 [11 12 13]
 [16 17 18]] 

Task2 original:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]] 

Task 2 required:
 [[ 1  3  5]
 [ 7  9 11]] 

Task 3 required:
 [1 3 4 7] 

Task 4:
 [[ 1  3]
 [11 13]
 [16 18]] 

Task 5:
 [15 12 18] 

Task 6:
 [[ 6 12  0  4  0]
 [ 0 15  0 14 15]
 [ 2  2  0  0  3]
 [ 0 10  7  1  0]
 [ 0  0  6  2 15]] 

Task 7:
 [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]] 

Task 8:
 [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]] 

Task 9:
 [[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]] 

Task 10:
 [[[ 2.  3.  4.  5.]
  [ 6.  7.  8.  9.]
  [10. 11. 12. 13.]]

 [[ 2.  3.  4.  5.]
  [ 6.  7.  8.  9.]
  [10. 11. 12. 13.]]] 

Task 11:
 [[ 1  4  7]
 [11 14 17]
 [21 24 27]] 

Task 12:
 [[[-1 -1]
  [-1 -1]
  [-1 -1]]

 [[ 5  5]
  [ 5  5]
  [ 5  5]]

 [[11 11]
  [11 11]
  [11 11]]

 [[17 17]
  [17 17]
  [17 17]]] 

Task 13:
 [ 0  6 12 18 24] 

Task 14:
 [[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 